"""Deterministically generate the first TypeScript namespace slice."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

from tools.codegen.models import (
    NamespaceSpec,
    OptionalListDomain,
    RequiredDomain,
    SearchReadOperation,
    WriteOperation,
)

SPEC_PATH = Path("spec/v1/namespaces/projects.yaml")
OUTPUT_PATH = Path("packages/typescript/src/generated/projects.ts")


def _load_spec(root: Path) -> NamespaceSpec:
    raw: Any = yaml.safe_load((root / SPEC_PATH).read_text(encoding="utf-8"))
    return NamespaceSpec.model_validate(raw)


def _constant_name(value: str) -> str:
    chars: list[str] = []
    for char in value:
        if char.isupper() and chars:
            chars.append("_")
        chars.append(char.upper())
    return "PROJECT_" + "".join(chars)


def _ts(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _render_search_read(operation: SearchReadOperation) -> str:
    fields = _constant_name(operation.fields)
    domain = operation.domain
    if domain is None:
        signature = "()"
        domain_line = "const domain: Domain = [];"
    elif isinstance(domain, OptionalListDomain):
        signature = f"({domain.parameter}: number | null = null)"
        domain_line = (
            f"const domain: Domain = {domain.parameter} === null ? [] : "
            f"[[{_ts(domain.field)},{_ts(domain.operator)},[{domain.parameter}]]];"
        )
    elif isinstance(domain, RequiredDomain):
        signature = f"({domain.parameter}: number)"
        domain_line = (
            f"const domain: Domain = [[{_ts(domain.field)},{_ts(domain.operator)},"
            f"{domain.parameter}]];"
        )
    else:  # pragma: no cover - discriminated validation makes this unreachable
        raise AssertionError("unknown domain")
    return f"""  async {operation.name}{signature}: Promise<OdooRecord[]> {{
    {domain_line}
    return this.client.searchRead({_ts(operation.model)}, {{
      domain,
      fields: {fields},
      order: {_ts(operation.order)},
    }});
  }}"""


def _render_write(operation: WriteOperation) -> str:
    return f"""  {operation.name}({operation.id_parameter}: number): Promise<boolean> {{
    return this.client.write(
      {_ts(operation.model)},
      [{operation.id_parameter}],
      {_ts(operation.values)},
    );
  }}"""


def render(spec: NamespaceSpec) -> str:
    canonical = json.dumps(spec.model_dump(mode="json", by_alias=True), sort_keys=True).encode()
    digest = hashlib.sha256(canonical).hexdigest()[:16]
    lines = [
        "// DO NOT EDIT — generated by python -m tools.codegen.",
        f"// Source: {SPEC_PATH.as_posix()}",
        f"// Spec digest: sha256:{digest}",
        "",
        'import type { OdooClientApi } from "../client-api.js";',
        'import { decodeRecordDates } from "../dates.js";',
        'import { DomainNamespace } from "../namespaces/domain.js";',
        'import type { Domain, OdooRecord } from "../types.js";',
        "",
        f"export const PROJECT_MODEL = {_ts(spec.model)};",
        f"export const PROJECT_DEFAULT_FIELDS = {_ts(spec.default_fields)} as const;",
        (
            "export const PROJECT_DEFAULT_DETAIL_FIELDS = "
            f"{_ts(spec.default_detail_fields)} as const;"
        ),
        f"export const PROJECT_DATE_FIELDS = {_ts(spec.date_fields)} as const;",
    ]
    for name, fields in spec.field_sets.items():
        lines.append(f"export const {_constant_name(name)} = {_ts(fields)} as const;")
    lines.extend(
        [
            "",
            "export abstract class GeneratedProjectNamespace extends DomainNamespace {",
            "  constructor(client: OdooClientApi) {",
            "    super(client, {",
            "      model: PROJECT_MODEL,",
            "      defaultFields: PROJECT_DEFAULT_FIELDS,",
            "      defaultDetailFields: PROJECT_DEFAULT_DETAIL_FIELDS,",
            "    });",
            "  }",
            "",
            "  protected override decodeRecord(record: OdooRecord): OdooRecord {",
            "    return decodeRecordDates(record, PROJECT_DATE_FIELDS);",
            "  }",
            "",
        ]
    )
    rendered_operations: list[str] = []
    for operation in spec.operations:
        if isinstance(operation, SearchReadOperation):
            rendered_operations.append(_render_search_read(operation))
        elif isinstance(operation, WriteOperation):
            rendered_operations.append(_render_write(operation))
    lines.append("\n\n".join(rendered_operations))
    lines.extend(["}", ""])
    return "\n".join(lines)


def generate(root: Path | None = None) -> Path:
    root = root or Path.cwd()
    output = root / OUTPUT_PATH
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(_load_spec(root)), encoding="utf-8")
    return output


def check_generated(root: Path | None = None) -> bool:
    root = root or Path.cwd()
    output = root / OUTPUT_PATH
    expected = render(_load_spec(root))
    return output.exists() and output.read_text(encoding="utf-8") == expected
