"""Deterministically generate SDK namespace slices from the finite Vodoo IR."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

import yaml

from tools.codegen.models import (
    NamespaceSpec,
    OptionalDomain,
    OptionalListDomain,
    RequiredDomain,
    SearchReadOperation,
    WriteOperation,
)

SPEC_DIR = Path("spec/v1/namespaces")
SPEC_GLOB = "*.yaml"
SPEC_PATH = SPEC_DIR / "projects.yaml"  # Backward-compatible project-spec alias.
TYPESCRIPT_OUTPUT_DIR = Path("packages/typescript/src/generated")
PYTHON_OUTPUT_DIR = Path("src/vodoo/generated")
ASYNC_PYTHON_OUTPUT_DIR = Path("src/vodoo/aio/generated")
TYPESCRIPT_OUTPUT_PATH = TYPESCRIPT_OUTPUT_DIR / "projects.ts"
PYTHON_OUTPUT_PATH = PYTHON_OUTPUT_DIR / "projects.py"
ASYNC_PYTHON_OUTPUT_PATH = ASYNC_PYTHON_OUTPUT_DIR / "projects.py"
OUTPUT_PATH = TYPESCRIPT_OUTPUT_PATH  # Backward-compatible alias for tooling imports.
OUTPUT_PATHS = (
    TYPESCRIPT_OUTPUT_PATH,
    PYTHON_OUTPUT_PATH,
    ASYNC_PYTHON_OUTPUT_PATH,
)
_GENERATED_MARKER = "DO NOT EDIT — generated by python -m tools.codegen."


def _load_spec(root: Path, path: Path = SPEC_PATH) -> NamespaceSpec:
    raw: Any = yaml.safe_load((root / path).read_text(encoding="utf-8"))
    return NamespaceSpec.model_validate(raw)


def _load_specs(root: Path) -> tuple[NamespaceSpec, ...]:
    paths = sorted((root / SPEC_DIR).glob(SPEC_GLOB))
    if not paths:
        raise FileNotFoundError(f"No namespace specifications found under {root / SPEC_DIR}")
    specs_list: list[NamespaceSpec] = []
    for path in paths:
        spec = _load_spec(root, path.relative_to(root))
        if path.stem != spec.namespace:
            raise ValueError(f"spec filename {path.name!r} must match namespace {spec.namespace!r}")
        specs_list.append(spec)
    specs = tuple(specs_list)
    namespaces = [spec.namespace for spec in specs]
    if len(namespaces) != len(set(namespaces)):
        raise ValueError("namespace specifications must have unique namespace names")
    class_names = [spec.class_name for spec in specs]
    if len(class_names) != len(set(class_names)):
        raise ValueError("namespace specifications must have unique class names")
    return specs


def _source_path(spec: NamespaceSpec) -> Path:
    return SPEC_DIR / f"{spec.namespace}.yaml"


def _output_paths(spec: NamespaceSpec) -> tuple[Path, Path, Path]:
    stem = spec.namespace
    return (
        TYPESCRIPT_OUTPUT_DIR / f"{stem}.ts",
        PYTHON_OUTPUT_DIR / f"{stem}.py",
        ASYNC_PYTHON_OUTPUT_DIR / f"{stem}.py",
    )


def all_output_paths(root: Path | None = None) -> tuple[Path, ...]:
    root = root or Path.cwd()
    return tuple(path for spec in _load_specs(root) for path in _output_paths(spec))


def _snake_case(value: str) -> str:
    with_word_boundaries = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", value)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", with_word_boundaries).lower()


def _constant_prefix(spec: NamespaceSpec) -> str:
    return _snake_case(spec.class_name).upper()


def _typescript_constant_name(spec: NamespaceSpec, value: str) -> str:
    return f"{_constant_prefix(spec)}_{_snake_case(value).upper()}"


def _python_constant_name(value: str) -> str:
    snake = _snake_case(value)
    if snake.endswith("ies"):
        snake = f"{snake[:-3]}y"
    elif snake.endswith("s"):
        snake = snake[:-1]
    return f"{snake.upper()}_FIELDS"


def _typescript_literal(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _typescript_doc(value: str) -> str:
    return value.replace("*/", "*\\/").replace("\n", "\n   * ")


def _python_literal(value: object) -> str:  # noqa: PLR0911
    if value is None:
        return "None"
    if value is True:
        return "True"
    if value is False:
        return "False"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, int | float):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(_python_literal(item) for item in value) + "]"
    if isinstance(value, dict):
        pairs = (f"{_python_literal(key)}: {_python_literal(item)}" for key, item in value.items())
        return "{" + ", ".join(pairs) + "}"
    raise TypeError(f"Unsupported generated literal: {type(value).__name__}")


def _python_string_list(values: list[str], *, indent: int = 0) -> str:
    prefix = " " * indent
    item_prefix = " " * (indent + 4)
    lines = ["["]
    lines.extend(f"{item_prefix}{_python_literal(value)}," for value in values)
    lines.append(f"{prefix}]")
    return "\n".join(lines)


def _spec_digest(spec: NamespaceSpec) -> str:
    canonical = json.dumps(spec.model_dump(mode="json", by_alias=True), sort_keys=True).encode()
    return hashlib.sha256(canonical).hexdigest()[:16]


def _render_typescript_search_read(
    spec: NamespaceSpec,
    operation: SearchReadOperation,
) -> str:
    fields = _typescript_constant_name(spec, operation.fields)
    domain = operation.domain
    if domain is None:
        signature = "()"
        domain_line = "const domain: Domain = [];"
    elif isinstance(domain, OptionalListDomain):
        signature = f"({domain.parameter}: number | null = null)"
        domain_line = (
            f"const domain: Domain = {domain.parameter} === null ? [] : "
            f"[[{_typescript_literal(domain.field)},{_typescript_literal(domain.operator)},"
            f"[{domain.parameter}]]];"
        )
    elif isinstance(domain, OptionalDomain):
        signature = f"({domain.parameter}: number | null = null)"
        domain_line = (
            f"const domain: Domain = {domain.parameter} === null ? [] : "
            f"[[{_typescript_literal(domain.field)},{_typescript_literal(domain.operator)},"
            f"{domain.parameter}]];"
        )
    elif isinstance(domain, RequiredDomain):
        signature = f"({domain.parameter}: number)"
        domain_line = (
            f"const domain: Domain = [[{_typescript_literal(domain.field)},"
            f"{_typescript_literal(domain.operator)},{domain.parameter}]];"
        )
    else:  # pragma: no cover - discriminated validation makes this unreachable
        raise AssertionError("unknown domain")
    request = f"""this.client.searchRead({_typescript_literal(operation.model)}, {{
      domain,
      fields: {fields},
      order: {_typescript_literal(operation.order)},
    }})"""
    date_fields = spec.field_set_date_fields.get(operation.fields)
    if date_fields:
        date_constant = _typescript_constant_name(spec, f"{operation.fields}DateFields")
        result = (
            f"const records = await {request};\n"
            f"    return records.map((record) => decodeRecordDates(record, {date_constant}));"
        )
    else:
        result = f"return {request};"
    return f"""  /** {_typescript_doc(operation.description)} */
  async {operation.name}{signature}: Promise<OdooRecord[]> {{
    {domain_line}
    {result}
  }}"""


def _render_typescript_write(operation: WriteOperation) -> str:
    return f"""  /** {_typescript_doc(operation.description)} */
  {operation.name}({operation.id_parameter}: number): Promise<boolean> {{
    return this.client.write(
      {_typescript_literal(operation.model)},
      [{operation.id_parameter}],
      {_typescript_literal(operation.values)},
    );
  }}"""


def render_typescript(spec: NamespaceSpec) -> str:
    digest = _spec_digest(spec)
    prefix = _constant_prefix(spec)
    source_path = _source_path(spec)
    record_types = (
        "Domain, OdooRecord"
        if any(isinstance(operation, SearchReadOperation) for operation in spec.operations)
        else "OdooRecord"
    )
    lines = [
        f"// {_GENERATED_MARKER}",
        f"// Source: {source_path.as_posix()}",
        f"// Spec digest: sha256:{digest}",
        "",
        'import type { OdooClientApi } from "../client-api.js";',
        'import { decodeRecordDates } from "../dates.js";',
        'import { DomainNamespace } from "../namespaces/domain.js";',
        f'import type {{ {record_types} }} from "../types.js";',
        "",
        f"export const {prefix}_MODEL = {_typescript_literal(spec.model)};",
        (
            f"export const {prefix}_DEFAULT_FIELDS = "
            f"{_typescript_literal(spec.default_fields)} as const;"
        ),
        (
            f"export const {prefix}_DEFAULT_DETAIL_FIELDS = "
            f"{_typescript_literal(spec.default_detail_fields)}"
            f"{' as const' if spec.default_detail_fields is not None else ''};"
        ),
        f"export const {prefix}_DATE_FIELDS = {_typescript_literal(spec.date_fields)} as const;",
    ]
    for name, fields in spec.field_sets.items():
        lines.append(
            f"export const {_typescript_constant_name(spec, name)} = "
            f"{_typescript_literal(fields)} as const;"
        )
    for name, fields in spec.field_set_date_fields.items():
        lines.append(
            f"export const {_typescript_constant_name(spec, f'{name}DateFields')} = "
            f"{_typescript_literal(fields)} as const;"
        )
    lines.extend(
        [
            "",
            (
                f"export abstract class Generated{spec.class_name}Namespace "
                "extends DomainNamespace {"
            ),
            "  constructor(client: OdooClientApi) {",
            "    super(client, {",
            f"      model: {prefix}_MODEL,",
            f"      defaultFields: {prefix}_DEFAULT_FIELDS,",
        ]
    )
    if spec.default_detail_fields is not None:
        lines.append(f"      defaultDetailFields: {prefix}_DEFAULT_DETAIL_FIELDS,")
    if spec.tag_model is not None:
        lines.append(f"      tagModel: {_typescript_literal(spec.tag_model)},")
    lines.extend(
        [
            "    });",
            "  }",
            "",
            "  protected override decodeRecord(record: OdooRecord): OdooRecord {",
            f"    return decodeRecordDates(record, {prefix}_DATE_FIELDS);",
            "  }",
        ]
    )
    operations: list[str] = []
    for operation in spec.operations:
        if isinstance(operation, SearchReadOperation):
            operations.append(_render_typescript_search_read(spec, operation))
        elif isinstance(operation, WriteOperation):
            operations.append(_render_typescript_write(operation))
    if operations:
        lines.extend(["", "\n\n".join(operations)])
    lines.extend(["}", ""])
    return "\n".join(lines)


def _python_domain(operation: SearchReadOperation) -> tuple[str, list[str]]:
    domain = operation.domain
    if domain is None:
        return "self", ["domain: list[Any] = []"]

    parameter = _snake_case(domain.parameter)
    if isinstance(domain, OptionalListDomain):
        return (
            f"self, {parameter}: int | None = None",
            [
                "domain: list[Any] = []",
                f"if {parameter} is not None:",
                (
                    f"    domain.append(({_python_literal(domain.field)}, "
                    f"{_python_literal(domain.operator)}, [{parameter}]))"
                ),
            ],
        )
    if isinstance(domain, OptionalDomain):
        return (
            f"self, {parameter}: int | None = None",
            [
                "domain: list[Any] = []",
                f"if {parameter} is not None:",
                (
                    f"    domain.append(({_python_literal(domain.field)}, "
                    f"{_python_literal(domain.operator)}, {parameter}))"
                ),
            ],
        )
    if isinstance(domain, RequiredDomain):
        return (
            f"self, {parameter}: int",
            [
                (
                    f"domain: list[Any] = [({_python_literal(domain.field)}, "
                    f"{_python_literal(domain.operator)}, {parameter})]"
                )
            ],
        )
    raise AssertionError("unknown domain")  # pragma: no cover


def _render_python_search_read(operation: SearchReadOperation, *, async_mode: bool) -> str:
    signature, domain_lines = _python_domain(operation)
    if operation.python_keyword_only:
        signature = signature.replace("self, ", "self, *, ", 1)
    method_name = _snake_case(operation.name)
    await_prefix = "await " if async_mode else ""
    async_prefix = "async " if async_mode else ""
    fields = _python_constant_name(operation.fields)
    body = [
        f"    {async_prefix}def {method_name}({signature}) -> list[dict[str, Any]]:",
        f"        {_python_literal(operation.description)}",
    ]
    body.extend(f"        {line}" for line in domain_lines)
    body.extend(
        [
            f"        return {await_prefix}self._client.search_read(",
            f"            {_python_literal(operation.model)},",
            "            domain=domain,",
            f"            fields={fields},",
            f"            order={_python_literal(operation.order)},",
            "        )",
        ]
    )
    return "\n".join(body)


def _render_python_write(operation: WriteOperation, *, async_mode: bool) -> str:
    method_name = _snake_case(operation.name)
    parameter = _snake_case(operation.id_parameter)
    await_prefix = "await " if async_mode else ""
    async_prefix = "async " if async_mode else ""
    return "\n".join(
        [
            f"    {async_prefix}def {method_name}(self, {parameter}: int) -> bool:",
            f"        {_python_literal(operation.description)}",
            f"        return {await_prefix}self._client.write(",
            f"            {_python_literal(operation.model)},",
            f"            [{parameter}],",
            f"            {_python_literal(operation.values)},",
            "        )",
        ]
    )


def _python_operations(spec: NamespaceSpec, *, async_mode: bool) -> str:
    rendered: list[str] = []
    for operation in spec.operations:
        if isinstance(operation, SearchReadOperation):
            rendered.append(_render_python_search_read(operation, async_mode=async_mode))
        elif isinstance(operation, WriteOperation):
            rendered.append(_render_python_write(operation, async_mode=async_mode))
    return "\n\n".join(rendered)


def render_python(spec: NamespaceSpec) -> str:
    digest = _spec_digest(spec)
    source_path = _source_path(spec)
    class_name = spec.class_name
    typing_import = (
        "Any, ClassVar"
        if any(isinstance(operation, SearchReadOperation) for operation in spec.operations)
        else "ClassVar"
    )
    module_docstring = (
        f'"""Generated {class_name.lower()} namespace metadata and simple '
        'synchronous operations."""'
    )
    lines = [
        module_docstring,
        "",
        f"# {_GENERATED_MARKER}",
        f"# Source: {source_path.as_posix()}",
        f"# Spec digest: sha256:{digest}",
        "",
        "from __future__ import annotations",
        "",
        f"from typing import {typing_import}",
        "",
        "from vodoo._domain import DomainNamespace",
        "",
    ]
    for name, fields in spec.field_sets.items():
        lines.extend(
            [
                f"{_python_constant_name(name)}: list[str] = {_python_string_list(fields)}",
                "",
            ]
        )
    lines.append("")
    lines.extend(
        [
            f"class _Generated{class_name}Attrs:",
            f'    """Shared generated attributes for {class_name.lower()} namespaces."""',
            "",
            f"    _model = {_python_literal(spec.model)}",
        ]
    )
    if spec.tag_model is not None:
        lines.append(f"    _tag_model: ClassVar[str | None] = {_python_literal(spec.tag_model)}")
    lines.extend(
        [
            "    _default_fields: ClassVar[list[str]] = "
            + _python_string_list(spec.default_fields, indent=4),
            "    _default_detail_fields: ClassVar[list[str] | None] = "
            + (
                _python_string_list(spec.default_detail_fields, indent=4)
                if spec.default_detail_fields is not None
                else "None"
            ),
            f"    _record_type = {_python_literal(spec.record_type)}",
            "",
            "",
            (
                f"class Generated{class_name}Namespace("
                f"_Generated{class_name}Attrs, DomainNamespace):"
            ),
            f'    """Generated synchronous {class_name.lower()} namespace operations."""',
        ]
    )
    operations = _python_operations(spec, async_mode=False)
    if operations:
        lines.extend(["", operations])
    lines.append("")
    return "\n".join(lines)


def render_async_python(spec: NamespaceSpec) -> str:
    digest = _spec_digest(spec)
    source_path = _source_path(spec)
    class_name = spec.class_name
    uses_any = any(isinstance(operation, SearchReadOperation) for operation in spec.operations)
    constants = sorted(
        {
            _python_constant_name(operation.fields)
            for operation in spec.operations
            if isinstance(operation, SearchReadOperation)
        }
    )
    attrs_name = f"_Generated{class_name}Attrs"
    imported_names = [*constants, attrs_name]
    import_block = "\n".join(f"    {name}," for name in imported_names)
    module_docstring = (
        f'"""Generated {class_name.lower()} namespace metadata and simple '
        'asynchronous operations."""'
    )
    lines = [
        module_docstring,
        "",
        f"# {_GENERATED_MARKER}",
        f"# Source: {source_path.as_posix()}",
        f"# Spec digest: sha256:{digest}",
        "",
        "from __future__ import annotations",
        "",
    ]
    if uses_any:
        lines.extend(["from typing import Any", ""])
    lines.extend(
        [
            "from vodoo.aio._domain import AsyncDomainNamespace",
            f"from vodoo.generated.{spec.namespace} import (",
            import_block,
            ")",
            "",
            "",
            (f"class GeneratedAsync{class_name}Namespace({attrs_name}, AsyncDomainNamespace):"),
            f'    """Generated asynchronous {class_name.lower()} namespace operations."""',
        ]
    )
    operations = _python_operations(spec, async_mode=True)
    if operations:
        lines.extend(["", operations])
    lines.append("")
    return "\n".join(lines)


def _rendered_outputs(spec: NamespaceSpec) -> dict[Path, str]:
    typescript, python, async_python = _output_paths(spec)
    return {
        typescript: render_typescript(spec),
        python: render_python(spec),
        async_python: render_async_python(spec),
    }


def _all_rendered_outputs(root: Path) -> dict[Path, str]:
    return {
        path: content
        for spec in _load_specs(root)
        for path, content in _rendered_outputs(spec).items()
    }


def generate(root: Path | None = None) -> tuple[Path, ...]:
    root = root or Path.cwd()
    outputs = _all_rendered_outputs(root)
    generated: list[Path] = []
    for relative_path, content in outputs.items():
        output = root / relative_path
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8")
        generated.append(output)
    return tuple(generated)


def _orphaned_outputs(root: Path, expected: set[Path]) -> tuple[Path, ...]:
    orphans: list[Path] = []
    for directory, suffix in (
        (TYPESCRIPT_OUTPUT_DIR, "*.ts"),
        (PYTHON_OUTPUT_DIR, "*.py"),
        (ASYNC_PYTHON_OUTPUT_DIR, "*.py"),
    ):
        for output in sorted((root / directory).glob(suffix)):
            relative = output.relative_to(root)
            if relative in expected:
                continue
            if _GENERATED_MARKER in output.read_text(encoding="utf-8"):
                orphans.append(relative)
    return tuple(orphans)


def stale_outputs(root: Path | None = None) -> tuple[Path, ...]:
    root = root or Path.cwd()
    outputs = _all_rendered_outputs(root)
    stale = [
        relative_path
        for relative_path, expected in outputs.items()
        if not (root / relative_path).exists()
        or (root / relative_path).read_text(encoding="utf-8") != expected
    ]
    stale.extend(_orphaned_outputs(root, set(outputs)))
    return tuple(stale)


def check_generated(root: Path | None = None) -> bool:
    return not stale_outputs(root)
